-- Migration 012: Firewall Configuration Management
-- © After Dark Systems

-- Create firewall_configs table for storing iptables/ebtables configurations with version control
CREATE TABLE IF NOT EXISTS firewall_configs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_name VARCHAR(255) NOT NULL,
    config_type VARCHAR(20) NOT NULL CHECK (config_type IN ('iptables', 'ip6tables', 'ebtables')),
    config_data TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_firewall_configs_user_id ON firewall_configs(user_id);
CREATE INDEX IF NOT EXISTS idx_firewall_configs_device_name ON firewall_configs(device_name);
CREATE INDEX IF NOT EXISTS idx_firewall_configs_config_type ON firewall_configs(config_type);
CREATE INDEX IF NOT EXISTS idx_firewall_configs_user_device ON firewall_configs(user_id, device_name);
CREATE INDEX IF NOT EXISTS idx_firewall_configs_created_at ON firewall_configs(created_at DESC);

-- Create unique constraint for version control (user_id, device_name, config_type, version)
CREATE UNIQUE INDEX IF NOT EXISTS idx_firewall_configs_unique_version
    ON firewall_configs(user_id, device_name, config_type, version);

-- Create firewall_tags table for organizing configurations
CREATE TABLE IF NOT EXISTS firewall_tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    config_id UUID NOT NULL REFERENCES firewall_configs(id) ON DELETE CASCADE,
    tag_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for tag lookups
CREATE INDEX IF NOT EXISTS idx_firewall_tags_config_id ON firewall_tags(config_id);
CREATE INDEX IF NOT EXISTS idx_firewall_tags_tag_name ON firewall_tags(tag_name);

-- Create firewall_deployments table for tracking where configs are deployed
CREATE TABLE IF NOT EXISTS firewall_deployments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    config_id UUID NOT NULL REFERENCES firewall_configs(id) ON DELETE CASCADE,
    server_hostname VARCHAR(255) NOT NULL,
    server_ip VARCHAR(45), -- Support both IPv4 and IPv6
    deployed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deployed_by UUID REFERENCES users(id) ON DELETE SET NULL,
    deployment_status VARCHAR(20) DEFAULT 'success' CHECK (deployment_status IN ('success', 'failed', 'partial')),
    deployment_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for deployment tracking
CREATE INDEX IF NOT EXISTS idx_firewall_deployments_config_id ON firewall_deployments(config_id);
CREATE INDEX IF NOT EXISTS idx_firewall_deployments_server ON firewall_deployments(server_hostname);
CREATE INDEX IF NOT EXISTS idx_firewall_deployments_deployed_at ON firewall_deployments(deployed_at DESC);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_firewall_configs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
DROP TRIGGER IF EXISTS trigger_firewall_configs_updated_at ON firewall_configs;
CREATE TRIGGER trigger_firewall_configs_updated_at
    BEFORE UPDATE ON firewall_configs
    FOR EACH ROW
    EXECUTE FUNCTION update_firewall_configs_updated_at();

-- Insert migration record
INSERT INTO schema_migrations (version, description)
VALUES (12, 'Add firewall configuration management with version control')
ON CONFLICT (version) DO NOTHING;

-- Add helpful comments
COMMENT ON TABLE firewall_configs IS 'Stores iptables, ip6tables, and ebtables firewall configurations with version control';
COMMENT ON COLUMN firewall_configs.config_type IS 'Type of firewall: iptables (IPv4), ip6tables (IPv6), or ebtables (Layer 2 bridge)';
COMMENT ON COLUMN firewall_configs.version IS 'Auto-incrementing version number per device and config type';
COMMENT ON COLUMN firewall_configs.config_data IS 'Full firewall configuration in iptables-save or ebtables-save format';
COMMENT ON TABLE firewall_tags IS 'Tags for organizing and categorizing firewall configurations';
COMMENT ON TABLE firewall_deployments IS 'Tracks deployment history of firewall configurations to servers';

-- Sample data for testing (optional - uncomment if needed)
/*
-- Insert sample firewall config for testing
INSERT INTO firewall_configs (user_id, device_name, config_type, config_data, version, description)
SELECT
    id,
    'web-server-01',
    'iptables',
    E'# Generated by iptables-save v1.8.7\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n-A INPUT -i lo -j ACCEPT\n-A INPUT -p icmp -j ACCEPT\n-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT\n-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT\n-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT\n-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT\n-A INPUT -j DROP\nCOMMIT',
    1,
    'Initial web server firewall configuration'
FROM users
WHERE email = 'admin@veribits.com'
LIMIT 1;
*/

-- Grant permissions (adjust as needed for your setup)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON firewall_configs TO veribits_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON firewall_tags TO veribits_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON firewall_deployments TO veribits_app;

-- Display success message
DO $$
BEGIN
    RAISE NOTICE 'Migration 012 completed successfully!';
    RAISE NOTICE 'Created tables: firewall_configs, firewall_tags, firewall_deployments';
    RAISE NOTICE 'Firewall configuration management is now available';
END $$;
