#!/bin/bash
# © After Dark Systems
# Firewall Editor Test Suite
# Tests all functionality of the firewall configuration management system

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
API_URL="${API_URL:-http://localhost:8080}"
TEST_EMAIL="firewall-test-$(date +%s)@example.com"
TEST_PASSWORD="TestPassword123!"
AUTH_TOKEN=""
API_KEY=""
CONFIG_ID=""

# Test counters
TESTS_PASSED=0
TESTS_FAILED=0

# Helper functions
log_test() {
    echo -e "${BLUE}[TEST]${NC} $1"
}

log_pass() {
    echo -e "${GREEN}[PASS]${NC} $1"
    ((TESTS_PASSED++))
}

log_fail() {
    echo -e "${RED}[FAIL]${NC} $1"
    ((TESTS_FAILED++))
}

log_info() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

# Create test user
create_test_user() {
    log_test "Creating test user"

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/auth/register" \
        -H "Content-Type: application/json" \
        -d "{
            \"email\": \"${TEST_EMAIL}\",
            \"password\": \"${TEST_PASSWORD}\",
            \"tier\": \"premium\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "Test user created"
        return 0
    else
        log_fail "Failed to create test user: $RESPONSE"
        return 1
    fi
}

# Login and get token
login_user() {
    log_test "Logging in test user"

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/auth/login" \
        -H "Content-Type: application/json" \
        -c /tmp/cookies.txt \
        -d "{
            \"email\": \"${TEST_EMAIL}\",
            \"password\": \"${TEST_PASSWORD}\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        AUTH_TOKEN=$(echo "$RESPONSE" | grep -o '"token":"[^"]*' | cut -d'"' -f4)
        log_pass "User logged in successfully"
        log_info "Token: ${AUTH_TOKEN:0:20}..."
        return 0
    else
        log_fail "Failed to login: $RESPONSE"
        return 1
    fi
}

# Create API key
create_api_key() {
    log_test "Creating API key"

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/api-keys" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -d "{
            \"description\": \"Firewall test key\",
            \"tier\": \"premium\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        API_KEY=$(echo "$RESPONSE" | grep -o '"api_key":"[^"]*' | cut -d'"' -f4)
        log_pass "API key created"
        log_info "API Key: ${API_KEY:0:20}..."
        return 0
    else
        log_fail "Failed to create API key: $RESPONSE"
        return 1
    fi
}

# Test 1: Upload iptables configuration
test_upload_config() {
    log_test "Test 1: Upload iptables configuration"

    # Create sample iptables config
    cat > /tmp/test-firewall.rules << 'EOF'
# Generated by iptables-save v1.8.7
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
COMMIT
EOF

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/upload" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -F "config_file=@/tmp/test-firewall.rules" \
        -F "firewall_type=iptables" \
        -F "device_name=test-server-01")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "Configuration uploaded successfully"

        # Verify parsed data
        if echo "$RESPONSE" | grep -q '"total_rules"'; then
            RULE_COUNT=$(echo "$RESPONSE" | grep -o '"total_rules":[0-9]*' | cut -d':' -f2)
            log_info "Parsed ${RULE_COUNT} rules"

            if [[ $RULE_COUNT -eq 6 ]]; then
                log_pass "Rule count matches expected (6)"
            else
                log_fail "Rule count mismatch. Expected 6, got ${RULE_COUNT}"
            fi
        fi
    else
        log_fail "Failed to upload configuration: $RESPONSE"
    fi

    rm -f /tmp/test-firewall.rules
}

# Test 2: Save configuration
test_save_config() {
    log_test "Test 2: Save firewall configuration"

    CONFIG_DATA=$(cat << 'EOF'
# Test firewall configuration
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp --dport 22 -m comment --comment "SSH access" -j ACCEPT
-A INPUT -p tcp --dport 443 -m comment --comment "HTTPS access" -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
COMMIT
EOF
)

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/save" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -d "{
            \"config_type\": \"iptables\",
            \"config_data\": $(echo "$CONFIG_DATA" | jq -Rs .),
            \"device_name\": \"test-server-01\",
            \"description\": \"Test configuration v1\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        CONFIG_ID=$(echo "$RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
        VERSION=$(echo "$RESPONSE" | grep -o '"version":[0-9]*' | cut -d':' -f2)
        log_pass "Configuration saved (ID: ${CONFIG_ID:0:8}..., Version: ${VERSION})"
    else
        log_fail "Failed to save configuration: $RESPONSE"
    fi
}

# Test 3: List configurations
test_list_configs() {
    log_test "Test 3: List saved configurations"

    RESPONSE=$(curl -s -X GET "${API_URL}/api/v1/firewall/list?device_name=test-server-01" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt)

    if echo "$RESPONSE" | grep -q '"success":true'; then
        TOTAL=$(echo "$RESPONSE" | grep -o '"total":[0-9]*' | cut -d':' -f2)
        log_pass "Retrieved configuration list (Total: ${TOTAL})"

        if [[ $TOTAL -gt 0 ]]; then
            log_pass "At least one configuration exists"
        else
            log_fail "No configurations found"
        fi
    else
        log_fail "Failed to list configurations: $RESPONSE"
    fi
}

# Test 4: Get specific configuration
test_get_config() {
    log_test "Test 4: Get specific configuration"

    if [[ -z "$CONFIG_ID" ]]; then
        log_fail "No CONFIG_ID available (Test 2 may have failed)"
        return
    fi

    RESPONSE=$(curl -s -X GET "${API_URL}/api/v1/firewall/get?id=${CONFIG_ID}" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt)

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "Retrieved configuration successfully"

        # Verify config data exists
        if echo "$RESPONSE" | grep -q '"config_data"'; then
            log_pass "Configuration data present"
        else
            log_fail "Configuration data missing"
        fi
    else
        log_fail "Failed to get configuration: $RESPONSE"
    fi
}

# Test 5: Save second version for diff test
test_save_second_version() {
    log_test "Test 5: Save second version of configuration"

    CONFIG_DATA=$(cat << 'EOF'
# Test firewall configuration v2
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp --dport 2222 -m comment --comment "SSH on custom port" -j ACCEPT
-A INPUT -p tcp --dport 443 -m comment --comment "HTTPS access" -j ACCEPT
-A INPUT -p tcp --dport 8080 -m comment --comment "HTTP alt port" -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
COMMIT
EOF
)

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/save" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -d "{
            \"config_type\": \"iptables\",
            \"config_data\": $(echo "$CONFIG_DATA" | jq -Rs .),
            \"device_name\": \"test-server-01\",
            \"description\": \"Test configuration v2 - Changed SSH port\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        CONFIG_ID_V2=$(echo "$RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
        VERSION=$(echo "$RESPONSE" | grep -o '"version":[0-9]*' | cut -d':' -f2)
        log_pass "Second version saved (Version: ${VERSION})"
    else
        log_fail "Failed to save second version: $RESPONSE"
    fi
}

# Test 6: Compare versions (diff)
test_diff_versions() {
    log_test "Test 6: Compare two versions"

    if [[ -z "$CONFIG_ID" ]] || [[ -z "$CONFIG_ID_V2" ]]; then
        log_fail "Missing CONFIG_IDs for diff test"
        return
    fi

    RESPONSE=$(curl -s -X GET "${API_URL}/api/v1/firewall/diff?old=${CONFIG_ID}&new=${CONFIG_ID_V2}" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt)

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "Diff generated successfully"

        # Check for expected changes
        if echo "$RESPONSE" | grep -q "2222"; then
            log_pass "Diff shows SSH port change"
        else
            log_fail "Diff missing expected changes"
        fi
    else
        log_fail "Failed to generate diff: $RESPONSE"
    fi
}

# Test 7: Public API endpoint (get-iptables.php)
test_public_api() {
    log_test "Test 7: Public API endpoint"

    if [[ -z "$API_KEY" ]]; then
        log_fail "No API key available"
        return
    fi

    # Test text output
    RESPONSE=$(curl -s "${API_URL}/get-iptables.php?key=${API_KEY}&device=test-server-01&output=text")

    if echo "$RESPONSE" | grep -q "VeriBits Firewall Configuration"; then
        log_pass "Public API text output works"

        if echo "$RESPONSE" | grep -q "test-server-01"; then
            log_pass "Device name in output"
        else
            log_fail "Device name missing from output"
        fi
    else
        log_fail "Public API failed: $RESPONSE"
    fi

    # Test JSON output
    RESPONSE=$(curl -s "${API_URL}/get-iptables.php?key=${API_KEY}&device=test-server-01&output=json")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "Public API JSON output works"
    else
        log_fail "Public API JSON failed: $RESPONSE"
    fi
}

# Test 8: IPv6 configuration
test_ipv6_config() {
    log_test "Test 8: IPv6 (ip6tables) configuration"

    CONFIG_DATA=$(cat << 'EOF'
# IPv6 firewall configuration
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p ipv6-icmp -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
COMMIT
EOF
)

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/save" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -d "{
            \"config_type\": \"ip6tables\",
            \"config_data\": $(echo "$CONFIG_DATA" | jq -Rs .),
            \"device_name\": \"test-server-01\",
            \"description\": \"IPv6 firewall configuration\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "IPv6 configuration saved"
    else
        log_fail "Failed to save IPv6 configuration: $RESPONSE"
    fi
}

# Test 9: ebtables configuration
test_ebtables_config() {
    log_test "Test 9: ebtables (Layer 2) configuration"

    CONFIG_DATA=$(cat << 'EOF'
# ebtables configuration
*filter
:INPUT ACCEPT
:FORWARD ACCEPT
:OUTPUT ACCEPT
-A INPUT -p ARP -j ACCEPT
-A FORWARD -p IPv4 --ip-protocol tcp --ip-destination-port 80 -j ACCEPT
COMMIT
EOF
)

    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/save" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -d "{
            \"config_type\": \"ebtables\",
            \"config_data\": $(echo "$CONFIG_DATA" | jq -Rs .),
            \"device_name\": \"bridge-server-01\",
            \"description\": \"ebtables bridge configuration\"
        }")

    if echo "$RESPONSE" | grep -q '"success":true'; then
        log_pass "ebtables configuration saved"
    else
        log_fail "Failed to save ebtables configuration: $RESPONSE"
    fi
}

# Test 10: Rate limiting
test_rate_limiting() {
    log_test "Test 10: Rate limiting"

    # Make multiple rapid requests
    for i in {1..25}; do
        curl -s -X POST "${API_URL}/api/v1/firewall/upload" \
            -H "Authorization: Bearer ${AUTH_TOKEN}" \
            -b /tmp/cookies.txt \
            -F "config_file=@-" \
            -F "firewall_type=iptables" \
            -F "device_name=rate-test" \
            <<< "test" > /dev/null 2>&1
    done

    # Should hit rate limit
    RESPONSE=$(curl -s -X POST "${API_URL}/api/v1/firewall/upload" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -b /tmp/cookies.txt \
        -F "config_file=@-" \
        -F "firewall_type=iptables" \
        -F "device_name=rate-test" \
        <<< "test")

    if echo "$RESPONSE" | grep -q "429\|rate limit"; then
        log_pass "Rate limiting is working"
    else
        log_info "Rate limit may not have been hit (or limit is high)"
    fi
}

# Main test execution
main() {
    echo ""
    echo "======================================"
    echo "  Firewall Editor Test Suite"
    echo "  API URL: ${API_URL}"
    echo "======================================"
    echo ""

    # Setup
    create_test_user || exit 1
    login_user || exit 1
    create_api_key || exit 1

    echo ""
    echo "Running tests..."
    echo ""

    # Run all tests
    test_upload_config
    test_save_config
    test_list_configs
    test_get_config
    test_save_second_version
    test_diff_versions
    test_public_api
    test_ipv6_config
    test_ebtables_config
    test_rate_limiting

    # Cleanup
    rm -f /tmp/cookies.txt

    # Summary
    echo ""
    echo "======================================"
    echo "  Test Results"
    echo "======================================"
    echo -e "${GREEN}Passed: ${TESTS_PASSED}${NC}"
    echo -e "${RED}Failed: ${TESTS_FAILED}${NC}"
    echo "Total:  $((TESTS_PASSED + TESTS_FAILED))"
    echo "======================================"
    echo ""

    if [[ $TESTS_FAILED -eq 0 ]]; then
        echo -e "${GREEN}All tests passed! ✓${NC}"
        exit 0
    else
        echo -e "${RED}Some tests failed! ✗${NC}"
        exit 1
    fi
}

# Run tests
main "$@"
